export default {
  info: {
    400: '傳送參數有誤! 若有疑慮請洽意見反應',
    401: '未授權動作，請先登入!',
    403: '違反系統規則! 若有疑慮請洽意見反應',
    404: '網路資源不存在，若有疑慮請洽意見反應',
    428: '當前操作需啟用高手服務',
    500: '系統錯誤，請稍待再試或洽意見反應',
    502: '系統重新啟動中，請稍待',
    503: '系統重新啟動中，請稍待',
    'ac-token-faile': '會員憑證驗證失敗(AC token issue),請洽客服人員處理',
    'unavailable-member': '很抱歉目前查無此會員!! 可能暫停使用或取消刊登中，無法顯示。',
    'proxy-error': '公用系統重新啟動中, 請稍待再試或洽意見反應',
    'not-member': '會員功能，請先註冊會員',
    'new-to-enable': '請先完成啟用高手服務',
    'should-complete-info': '需填寫完整資訊，才能使用服務',
    'not-active': '尚未啟用會員身份，請先補填會員資料申請',
    'not-accept': '不接受動作，請確認流程是否正確，或洽客服人員處理',
    'not-enougth-money': '支付費用不足，請洽客服人員處理',
    'bad-credit': '限制帳戶，若有疑問請洽客服',
    'media-type-not-allow': '不支援的檔案格式動作, 請再重新上傳',
    'media-convert-failure': '上傳轉檔失敗, 請再重新上傳',
    'media-convert-timeout': '系統忙碌中, 上傳檔案逾時, 請稍後重新上傳',
    'tx-record-exception': '交易記錄異常，請洽客服人員處理',
    'cat-limit': '服務項目已滿 (最多二項)',
    'demand-cat-limit': '案件類別已滿 (最多二項)',
    'demand-closed': '案件己到期或關閉，動作無法進行，若有疑問，請洽客服人員處理',
    'serviceitem-invalid': '有部分條件未設定，請填寫完整以利案主搜尋',
    'disagree-deposit': '請勾選接受押金規範',
    'chat-upload-limit': '超過檔案上傳限制 5MB',
    'chat-in-communicated': '此案件己正在溝通中',
    'over-capacity-limit': '己超過可用聯絡次數',
    'over-demand-price-limit': '您目前的付費方案不適用案件',
    // demand-controller
    'same-as-demander': '您為此案件案主，不可應徵',
    'plz-choose-one-way-of-two-to-verify': '請完成以上室內電話或行動電話任一驗證方可送審',
    'plz-choose-one-way-of-three-to-verify': '請完成以上email、室內電話或行動電話任一驗證方可送審',
    'demand-has-been-submitted': '此需求已完成送審',
    // 收藏
    'has-been-favorited': '此服務已加入收藏',
    'do-not-favorite-your-gig': '無法收藏自己的服務',
    'no-gig-index-to-favorite': '此服務未開放',
    'no-favorite-to-delete': '無法取消收藏不存在的服務',
    // 成為高手 api
    'email-not-available': 'Email無法寄送或格式錯誤',
    'address-not-valid': '請正確填寫地址資料，不可有特殊字元符號',
    'email-duplicate': 'Email已被使用',
    'cellphone-verified': '此手機號碼已驗證！',
    'invoice-duplicate': '此統一編號重複使用',
    'identity-duplicate': '此身分證字號重複使用',
    'should-choose-one-input': '身分證及統一編號須擇一選填',
    'should-input-together': '需同時填寫',
    'cellphone-not-match': '輸入的手機號碼與已驗證的手機號碼不相符',
    'cellphone-not-verified': '手機號碼尚未驗證',
    'cellphone-should-not-be-empty': '行動電話資料不可刪除',
    'not-paied-to-publish-profile': '請先進行保證金流程',
    'must-have-one-gig': '至少需填寫一個服務項目!',
    // feedback api
    'profile-unpublished': '個人檔案未發布，無法取得評價列表',
    'review-not-exist': '評價資料不存在',

    // verify controller
    'invoice-not-valid': '請填寫正確統一編號',
    'cellphone-not-valid': '請填寫正確行動電話',
    // /verify/sendSMS/{who}  寄送 - 手機驗證碼
    'cellphone-been-used': '此行動電話已被其他帳號驗證',
    'cellphone-has-verified': '此行動電話已驗證',
    'more-than-three-times': '手機驗證碼發送超過每日 3 次限制',
    // /verify/cellphone/{who} 檢查 - 行動電話
    'token-error': '請填寫正確驗證碼',
    'token-expired': '驗證碼已失效，請重新發送驗證碼!',
    // /verify//identity/{who} 檢查- 身分證字號
    'identity-not-valid': '請填寫正確身分證',
    'ac-identity-duplicate': '您可能曾使用身分證註冊104帳號，請先使用身分證重新登入',
    'passport-not-valid': '請填寫正確護照號碼',
    mistype: '請選擇身分證/護照號碼',
    // payment controller
    'inviteCode-incorrect': '您輸入的邀請碼不正確，請確認後重新輸入。',
    'inviteCode-typeNotMatch': '您輸入的邀請碼不正確，請確認後重新輸入。',
    'inviteCode-used': '您輸入的邀請碼已使用，請確認後重新輸入。',
    'inviteCode-expired': '您輸入的邀請碼已失效，請確認後重新輸入。',
    'inviteCode-valueNotMatch': '您輸入的邀請碼與身份不符合，請確認後重新輸入。',
    // EDM
    'has-unsubscribed': '已取消訂閱電子報，不可重複取消。',
    'payload-error': '參數錯誤',
    'no-complete-gig': '該會員沒有完整的服務項目，不可訂閱最新案件報',
    'has-verified-contact': '電子信箱和行動電話至少一項完成驗證',
    'illegal-ranking1-score': '請填寫評價星數',
    'illegal-ranking2-score': '請填寫評價星數',
    'illegal-ranking3-score': '請填寫評價星數',
    'payload-error-from-CooperateByTopper-mail': '請由高手邀請確認合作信確認合作連結進入',
    'payload-error-from-AskReview-mail': '請由高手邀請評價通知信立即評價連結進入',
    'topper-cancelPublish-cannot-confirm-cooperate': '此高手已取消刊登，不可確認合作',
    'topper-cancelPublish-cannot-review': '此高手已取消刊登，不可給予評價',
    'account-deleted-cannot-confirm-cooperate': '帳號已不存在，無法確認合作',
    'account-deleted-cannot-review': '帳號已不存在，無法評價',
    // dealMeta流程
    'has-rejected': '已回絕邀請',
    'has-cooperated': '已確認合作',
    'has-reviewed': '已完成評價',
    'other-side-has-reported-cooperation': '對方已回報合作，請於對話內的訊息中點選回覆「確認合作」',
    'expired-deal-operation': '你已重覆點選！請重整更新頁面。',
    'cannot-apply-rejected-demand': '您先前已拒絕此案件邀請，無法再應徵！',
    'topper-cancelPublish-cannot-communicate': '此高手已取消刊登，不可同意溝通',
    'gig-desc-limit': '服務內容不可超過2500個字',
    'invalid-topperNotReply-leave': '高手尚未回覆邀請，不可退出聊天室！',
    'invalid-cooperating-leave': '有合作中案件，不可退出聊天室！',
    'invite-limit': '很抱歉，每案件最多邀請50位高手，您已達限制無法再邀請。',
    'should-choose-one-contact-input': '會員資料請填寫聯絡電話',
  }
};
