const routePath = {
  root: '/',
  marketing: '/join',
  chat: '/chat',
  editor: '/editor',
  serviceItems: '/serviceItems',
  editProfile: '/editProfile',
  success: '/success',
  shareSetting: '/shareSetting',
  payment: '/payment',
  search: '/search',
  searchT: '/search-tutor',
  demand: '/demand',
  evaluation: '/evaluation/:basicId',
  evaluationList: '/evaluationList',
  collection: '/collection',
  extend: '/extend',
  caseList: '/caseList',
  caseInfo: '/caseInfo',
  edmContent: '/edmContent',
  unsubscribe: '/unsubscribe',
  enableCaseUser: '/enableCaseUser',
  editCaseForm: '/editCaseForm',
  caseForm: '/caseForm',
  planSelect: '/planSelect',
  finished: '/finished',
  profile: '/profile/:basicId',
  service: '/service/:basicId',
  EvaluationEDM: '/evaluationedm',
  topperDashboard: '/topper-dashboard/home',
  topperDashboardList: '/topper-dashboard/list',
  topperDashboardPaidRecord: '/topper-dashboard/paid-record',
  topperDashboardInviting: '/topper-dashboard/inviting',
  topperDashboardCommunication: '/topper-dashboard/communication',
  topperDashboardCooperation: '/topper-dashboard/cooperation',
  topperDashboardClosed: '/topper-dashboard/closed',
  topperDashboardApplied: '/topper-dashboard/applied',
  topperDashboardContact: '/topper-dashboard/contact',
  publicationPlan: '/publication-plan',
  candidate: '/demand/candidate',
  invitees: '/demand/invitees',
  joinCaseForm: '/joincaseForm',
  upgradePlan: '/upgrade',
  upgradePayment: '/upgrade-pay',
  upgradeSuccess: '/upgrade-success',
};

export default routePath;
