export default {
  info: {
    400: '傳送參數有誤! 若有疑慮請洽工程人員確認',
    401: '未授權動作，請先登入!',
    403: '未登入 或 登入錯誤，請確認帳密輸入是否正確!',
    404: '網路資源不存在，若有疑慮請洽工程人員確認',
    500: '系統錯誤，請稍待再試或洽工程人員確認',
    502: '系統重新啟動中，請稍待',
    503: '系統重新啟動中，請稍待',
    'proxy-error': '公用系統重新啟動中, 請稍待再試或洽工程人員確認',
    'not-accept': '不接受動作，請確認流程是否正確，或洽工程人員確認',
    'email-not-available': 'Email已驗證或已被使用',
    'email-not-valid': 'Email格式錯誤',
    'address-not-valid': '請正確填寫地址資料，不可有特殊字元符號',
    'token-expired': '驗證時效已超過30分鐘，請重新發送驗證碼!',
    'token-error': '手機驗證碼輸入錯誤',
    'tx-record-exception': '交易記錄異常，請洽洽工程人員確認',
    'invoice-duplicate': '此統一編號重複使用',
    'identity-duplicate': '此身分證字號重複使用',
    'incorrect-invoice-info': '請輸入正確的公司資訊相關欄位',
    'should-choose-one-input': '身分證及統一編號須擇一選填',
    'should-choose-one-contact-input': '手機或室內電話需擇一填寫',
    'should-choose-roleType': '請選擇身分類別',
    'should-input-together': '需同時填寫',
    'cellphone-not-match': '輸入的手機號碼與已驗證的手機號碼不相符',
    'cellphone-not-verified': '手機號碼尚未驗證',
    'cellphone-verified': '此手機號碼已驗證！',
    'cat-limit': '服務項目已滿 (最多二項)',
    'invoice-not-valid': '統一編號格式錯誤!',
    'cellphone-not-valid': '驗證行動電話格式錯誤',
    'telephone-not-valid': '驗證室內電話格式錯誤',
    'should-choose-one-to-verify': '請選擇審核驗證通過的電話',
    'identity-not-valid': '身分證字號格式錯誤',
    'not-delete-yet': '該會員高手產品服務尚未刪除，請刪除後再回覆通知',
    'already-delete-top-service': '該會員高手產品服務已刪除，不可選擇已慰留',
    'passport-not-valid': '護照格式不正確!',
    'ac-identity-duplicate': '該身分證/護照已被使用!',
    'telArea-not-valid': '市內電話區碼格式錯誤',
    'should-type-identity': '請輸入身分證/護照欄位',
    'identity-should-not-be-empty': '不可刪除身分證/護照欄位',
    'should-type-cellphone': '請填寫行動電話',
    'should-type-email': '請填寫正確Email',
    'cellphone-should-not-be-empty': '不可刪除行動電話欄位',
    'cellphone-been-used': '此行動電話已被驗證，請修改號碼',
    'no-repeat-ids': '案件編號不可重複',
    'some-demand-illegal': '案件編號輸入錯誤',
    'should-choose-area': '請選擇地區',
    'should-choose-industry': '請選擇產業類別',
    'no-complete-gig': '該會員沒有完整的服務項目，不可訂閱最新案件報',
    'invalid-date': '請填寫正確評價日期',
    'invalid-delete-review': '非後台新增的評價不可刪除',
    'violation-not-confirm': '有被檢舉記錄，未查核確認前，不可取消刊登。',
    'demander-not-review': '合作中的案件尚未結案，不可取消刊登。',
    'topper-cancelPublish-cannot-report-cooperate': '此高手已取消刊登，不可回報合作',
    'demander-account-deleted-cannot-report-cooperate': '此案主已刪除會員，不可回報合作',
    'topper-cancelPublish-cannot-confirm-cooperate': '此高手已取消刊登，不可確認合作',
    'demander-account-deleted-cannot-confirm-cooperate': '此案主已刪除會員，不可確認合作',
    'topper-cancelPublish-cannot-ask-review': '此高手已取消刊登，不可邀請評價',
    'demander-account-deleted-cannot-ask-review': '此案主已刪除會員，不可邀請評價',
    'gig-target-require': '請填寫服務對象',
    'should-choose-educationalStage': '請填寫教學對象/年級',
    'invalid-educational-stage': '請填寫教學對象/年級',
    'invalid-educational-grade': '請填寫教學對象/年級',
    'test-account-cannot-delete': '此帳號已設定為測試帳號，需取消設定才可刪除。',
    'basicId-not-exist': '輸入的會員編號不正確',
    'no-permission': '沒有權限操作此步驟',
    'statistics-sales-non-exist': '選取的區間查無營收資料',
    'passed-expire-date': '下線日請勿早於今日，若需結束請直接設定結案下刊。',
    'invalid-future-date': '指定日期未有統計數字'
  }
};
